CliMA/ParameterEstimocean.jl

src/ModelsAndData/file_wrangling.jl
=> `sort!(iters)` in `get_iterations`

examples/convective_adjustment_perfect_model_calibration.jl
=> Fix bug in `convective_adjustment_perfect_model_calibration.jl`

.github/workflows/TagBot.yml
Slowly slowly preparing for package registration ;)
=> Adds TagBot gh action

src/TurbulenceClosureParameters.jl
`for j in size(closures, 2)` --> `for j in 1:size(closures, 2)`
=> Bug in update_closure_ensemble_member!

Manifest.toml, test/runtests.jl, test/test_ensemble_column_models.jl
After writing this up I realized it probably belongs in `Oceananigans` rather than here. But I'll open this anyways since it's illustrative. Next, I'll port these to Oceananigans.
Right now the test for multiple Coriolises fails, showing that there is a bug in Oceananigans when using multiple Coriolis parameters.
Related to #58 .
=> Adds tests that we can simulate ensemble of closures and Coriolises

Project.toml, README.md
=> Adds metadata + Zenodo

examples/perfect_baroclinic_adjustment_calibration.jl, examples/perfect_catke_calibration.jl, examples/perfect_convective_adjustment_calibration.jl, src/EnsembleKalmanInversions.jl
=> Fix iteration counting by `iterate!`

Project.toml, docs/make.jl
(#123 seems to have deleted them...)
=> Add back compat entries

src/InverseProblems.jl, src/Observations.jl, src/TurbulenceClosureParameters.jl, test/test_synthetic_observations.jl
Scoping problems prevented regridding from working properly.
=> Fix scoping issues in SyntheticObservations constructor

src/OceanTurbulenceParameterEstimation.jl, test/runtests.jl, test/test_lesbrary_datadeps.jl
I'd like also to add a test that all DataDeps links work.
=> Add DataDep links to four- and six-day suites

src/OceanTurbulenceParameterEstimation.jl, test/test_lesbrary_datadeps.jl
Two- and four-day suite urls, plus tests.
=> Add LESbrary data with 1m vertical resolution

codecov.yml, src/EnsembleKalmanInversions.jl
An attempt to remove Codecov annotations in PRs
=> Remove Codecov annotations

Project.toml, examples/five_case_catke_calibration.jl, examples/lesbrary_catke_calibration.jl, src/EnsembleKalmanInversions.jl, src/Observations.jl, src/OceanTurbulenceParameterEstimation.jl, test/runtests.jl, test/test_eki.jl, test/test_ensemble_kalman_inversion.jl
This PR implements a more general `Resampler` that can resample all particles (not just those that have failed). It also fixes the bug that caused #156 .
Closes #156 .
=> More general `Resampler`

src/InverseProblems.jl, test/test_forward_map.jl
The halo size wasn't being correctly passed on.
=> Fixes bug in drop_y_dimension

Manifest.toml, src/EnsembleKalmanInversions.jl, src/OceanTurbulenceParameterEstimation.jl, src/Parameters.jl, test/test_lesbrary_datadeps.jl
This PR represents an attempt to understand why, if a particle fails, resampling seems to succeed only temporarily (the particle fails again on the next iteration).
=> Debugging "persistent failed parameters"

Project.toml
=> Bump to 0.7.0

Project.toml, examples/perfect_baroclinic_adjustment_calibration.jl
=> Some fixes in the perfect baroclinic adjustment calibration example

src/Transformations.jl, test/test_transformations.jl
In the process I discovered we were missing a method:
```Julia
compute_time_transformation(weights::AbstractVector, fts) = weights
```
=> Adds Transform tests for weighting

src/Transformations.jl
https://www.loom.com/share/a56c57cf463b424285a74e9336240723
=> Convert Int to UnitRange in Time/SpaceIndices

docs/src/library/internals.md, docs/src/library/public.md, src/Parameters.jl, test/runtests.jl
=> Adds docstring in core-function inside `Parameters` module

docs/make.jl
What do you think?
Some examples were not really examples. They are just literated doc sections...
=> Restructuring of Docs

src/EnsembleKalmanInversions.jl, src/InverseProblems.jl
=> Some clean up of some suppressions

src/InverseProblems.jl, src/Observations.jl
@navidcy This is the data verification I was talking about. If we do this maybe we don't need to throw warnings a la #219 .
=> Verify data collection in `forward_map`

Project.toml
Think we neglected to bump after name change.
=> Bump to 0.12.0

src/InverseProblems.jl
=> Remove redundant variable definition

src/EnsembleKalmanInversions.jl
=> Fix incremental compilation error for `NormExceedsMedian`

src/InverseProblems.jl
=> Drop duplicate method definition

Manifest.toml, Project.toml, docs/Manifest.toml, docs/Project.toml
Hopefully GPU + SingleColumnGrid will work now.
=> Update Oceananigans v0.78.2

Project.toml
To capture upgrade to Oceananigans 0.79.1
=> Bump to 0.14.3
